### ISSUE TITLE
some clear cache links non-functional

### ISSUE THREAD

**Issue by unnecessarydave** [foxtrick-ng/foxtrick#25]
The clear cache button in the Foxtrick preferences page activates but does not seem to actually clear the cache.

The clear cache link in the toolbar menu is not even clickable.
```
Uncaught TypeError: Cannot read properties of null (reading 'href')
    at init (popup.js:92:69)
    at popup.js:105:2
```

The link at the bottom left of every page in hattrick does seem to work at least.

**Comment by unnecessarydave** [comment]
The broken clear cache link in the toolbar is simple enough.  A silly oversight by me when disabling the Contribute link caused this.

The clear cache button in the preferences page is trickier.  The code seems to operateunder the assumption that because preferences.html runs in the background context it will have the same global scope as the background page.  This is not the case.  Preferences instatiates its own copy of Foxtrick.session.__CACHE and clearing this will obviously have no effect on the copy referenced by the background page.

I _could_ fix this, but the prefs code logic is somewhat complex and I'll have to visit it again for the MV3 port, so the clear cache link on the prefs page will have to remain broken for now.

**Comment by unnecessarydave** [comment]
375f7fef94e366b8746d6a72969cebf43496e49b partially addresses this issue, restoring the functionality of the toolbar 'clear cache' link.
